### ISSUE TITLE
Python 3 'dict' object has no attribute 'has_key'

### ISSUE THREAD

**Issue by konsalex** [joshtronic/python-holidayapi#3]
Hello,

I tried to use a combo django with python3 and an error occurred to me : hapi.holidays(parameters)

After searching at python 3 `has_key` is removed from dictionaries.

**Comment by kairos35** [comment]
Got the same error - any news how to update the code?

**Comment by joshtronic** [comment]
Thanks for reminded me this was out there. Will try to get this resolved in the next day or so, but PRs are welcome :)
